// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.2
// source: pkg/proto/sportify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SubscriptionType:
	//
	//	*SubscriptionRequest_Team
	//	*SubscriptionRequest_Player
	SubscriptionType isSubscriptionRequest_SubscriptionType `protobuf_oneof:"subscription_type"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_pkg_proto_sportify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sportify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sportify_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionRequest) GetSubscriptionType() isSubscriptionRequest_SubscriptionType {
	if x != nil {
		return x.SubscriptionType
	}
	return nil
}

func (x *SubscriptionRequest) GetTeam() string {
	if x != nil {
		if x, ok := x.SubscriptionType.(*SubscriptionRequest_Team); ok {
			return x.Team
		}
	}
	return ""
}

func (x *SubscriptionRequest) GetPlayer() string {
	if x != nil {
		if x, ok := x.SubscriptionType.(*SubscriptionRequest_Player); ok {
			return x.Player
		}
	}
	return ""
}

type isSubscriptionRequest_SubscriptionType interface {
	isSubscriptionRequest_SubscriptionType()
}

type SubscriptionRequest_Team struct {
	Team string `protobuf:"bytes,1,opt,name=team,proto3,oneof"`
}

type SubscriptionRequest_Player struct {
	Player string `protobuf:"bytes,2,opt,name=player,proto3,oneof"`
}

func (*SubscriptionRequest_Team) isSubscriptionRequest_SubscriptionType() {}

func (*SubscriptionRequest_Player) isSubscriptionRequest_SubscriptionType() {}

type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_pkg_proto_sportify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sportify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sportify_proto_rawDescGZIP(), []int{1}
}

func (x *Update) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Update) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_sportify_proto protoreflect.FileDescriptor

var file_pkg_proto_sportify_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x53, 0x70, 0x6f, 0x72,
	0x74, 0x69, 0x66, 0x79, 0x22, 0x5a, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x74,
	0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x61,
	0x6d, 0x12, 0x18, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x13, 0x0a, 0x11, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x36, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4b, 0x0a, 0x09, 0x4e, 0x42, 0x41, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x3e, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x12, 0x1d, 0x2e, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x30, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x61, 0x73, 0x68, 0x61, 0x6e, 0x6d, 0x2f, 0x53, 0x70, 0x6f,
	0x72, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_proto_sportify_proto_rawDescOnce sync.Once
	file_pkg_proto_sportify_proto_rawDescData []byte
)

func file_pkg_proto_sportify_proto_rawDescGZIP() []byte {
	file_pkg_proto_sportify_proto_rawDescOnce.Do(func() {
		file_pkg_proto_sportify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_sportify_proto_rawDesc), len(file_pkg_proto_sportify_proto_rawDesc)))
	})
	return file_pkg_proto_sportify_proto_rawDescData
}

var file_pkg_proto_sportify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_sportify_proto_goTypes = []any{
	(*SubscriptionRequest)(nil), // 0: Sportify.SubscriptionRequest
	(*Update)(nil),              // 1: Sportify.Update
}
var file_pkg_proto_sportify_proto_depIdxs = []int32{
	0, // 0: Sportify.NBAStream.Subscribe:input_type -> Sportify.SubscriptionRequest
	1, // 1: Sportify.NBAStream.Subscribe:output_type -> Sportify.Update
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_sportify_proto_init() }
func file_pkg_proto_sportify_proto_init() {
	if File_pkg_proto_sportify_proto != nil {
		return
	}
	file_pkg_proto_sportify_proto_msgTypes[0].OneofWrappers = []any{
		(*SubscriptionRequest_Team)(nil),
		(*SubscriptionRequest_Player)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_sportify_proto_rawDesc), len(file_pkg_proto_sportify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_sportify_proto_goTypes,
		DependencyIndexes: file_pkg_proto_sportify_proto_depIdxs,
		MessageInfos:      file_pkg_proto_sportify_proto_msgTypes,
	}.Build()
	File_pkg_proto_sportify_proto = out.File
	file_pkg_proto_sportify_proto_goTypes = nil
	file_pkg_proto_sportify_proto_depIdxs = nil
}
